apiVersion: v1
kind: Service
metadata:
  namespace: sandbox
  name: techtrends
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 4111
    targetPort: 3111
  selector:
    app: techtrends
  